name: Auto Update

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2
    
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set variable
        env: 
          newHash: ${{ hashFiles('factory/resultant/gfw.list') }}
      
      - name: Install requests
        run: pip3 install requests

      - name: Update rules
        run: |
          cd factory
          python3 gfwlist.py
          python3 build_confs.py
          cd ..

      - name: Set variable
        env: 
          newHash: ${{ hashFiles('factory/resultant/gfw.list') }}
        run: echo "${{ env.oldHash }}" "${{ env.newHash }}"
        
      - name: Push commit
        if: ${{ env.oldHash != env.newHash }}
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'github-action@users.noreply.github.com'
          git commit -am "Automated update"
          git push origin master
